# ansible-galaxy install --roles-path=galaxy_roles/ -r install_roles.yml 

- src: geerlingguy.java
  version: 1.7.4

- src: geerlingguy.jenkins
  version: 3.2.1

- src: savoirfairelinux.nexus3-oss
  version: v1.4

- src: jdauphant.nginx
  version: v2.12.3
